### PR TITLE
Test if `signal` has attribute `SIGQUIT`

### LINKED ISSUE #46: Windows: module 'signal' has no attribute 'SIGQUIT'
When running `py manage.py worker` on Windows, I get the following:

``` sh
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```

Which is coming from here:

https://github.com/dabapps/django-db-queue/blob/d27fd08a9b11271dca23e42b37772f29727cef7c/django_dbq/management/commands/worker.py#L87

I was able to successfully run the worker and create jobs by modifying it like this:

``` py
if hasattr(signal, 'SIGQUIT'):
    signal.signal(signal.SIGQUIT, self.shutdown)
```

### PR DESCRIPTION
**Pull request by johncmacy**
Add support for Windows users, since Windows doesn't support the SIGQUIT signal.

Closes #46

### CODE REVIEW

**Comment by j4mie** [comment]
Thanks for this! I'm a little bit hesitant to merge this as I don't use Windows, and so I would have no way of supporting this if anyone reported a bug. And setting up infrastructure to run the CI on Windows would also be a huge pain. On the other hand, it's a very small change... let me think about it a little!

**Comment by j4mie** [comment]
Decided that we're happy to merge this. A couple of note:

1. The tests are failing because of black formatting, please run `black django_dbq` to fix.
2. Please add a note at the bottom of the README (perhaps straight after the `Testing` section) along these lines:

```
## Windows support

Windows is supported on a best-effort basis only, and is not covered by automated or manual testing.
```

Thanks again 🙂

**Comment by j4mie** [comment]
hey @johncmacy it looks like there's something very odd going on with Black. Could this be another Windows issue maybe? It looks like your Black and my Black are disagreeing.. 🤯 

Would you like me to pick this PR up and try to resolve the formatting issues?

**Comment by johncmacy** [comment]
@j4mie please do, I haven't used black before so not sure I'm going to be able to resolve it quickly. I wasn't able to pip install from test-requirements.txt either (some issue with psycopg2), so I am currently unable to run tests locally.

**Comment by j4mie** [comment]
@johncmacy no problem, leave it with me!

**Comment by j4mie** [comment]
Honestly I'm still a little confused by this, because it looks like Black has formatted a bit of code that you didn't even touch 🤔 oh well, it's passing now at least! Thanks again 🙂

**Review by j4mie — APPROVED** [review]

**Comment by johncmacy** [comment]
Thank you for approving this!

**Pull request merged**
